apiVersion: v1
kind: Service
metadata:
  name: portofolio-service
spec:
  type: NodePort # Membuka akses via IP Raspi
  selector:
    app: portofolio
  ports:
    - protocol: TCP
      port: 80        # Port di dalam Cluster
      targetPort: 80  # Port Container Nginx
      nodePort: 30080 # Webmu akan bisa diakses di http://IP-RASPI:30080